---
title: "English regional dialects"
output: html_document
date: '2022-06-09'
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

```{r, include = FALSE}
source(here::here("scripts", "00_libs.R"))
source(here("scripts", "01_helpers.R"))
source(here("scripts", "03_load_data.R"))

## define color palette 
cbPalette <- c("#999999", "#E69F00", "#56B4E9",
               "#009E73", "#F0E442", "#0072B2", 
               "#D55E00", "#CC79A7")

p1 = mds_plot(eng_mono) %>% 
  mutate(group = "English mono")

p2 = mds_plot(e_asian) %>% 
  mutate(group = "East Asian")

p3 = mds_plot(s_asian) %>% 
  mutate(group = "South Asian")

p4 = mds_plot(se_asian) %>% 
  mutate(group = "Southeast Asian")

p5 = mds_plot(non_multi) %>% 
  mutate(group = "Non multi")

plot_df = rbind(p1,p2,p3,p4,p5)
```

```{r}
plot_df %>%
  filter(group == "English mono") %>% 
  filter(lang_1 == "English") %>% 
  ggplot(aes(x, y, color = lang_3, label = lang_3)) +
  geom_point(size = .8, alpha = .6) + 
  geom_text(size = 1.3, hjust = -.15) +
  stat_ellipse(aes(x, y, color = lang_2), level = .8, linetype = "dashed", alpha = .5) +
  theme_minimal() + 
  ylab("Dimension 1") +
  xlab("Dimension 2") +
  labs(color = "Language Group") +
  scale_color_manual(values=cbPalette) +
  theme(legend.position = "none", legend.text=element_text(size=5),
        legend.title=element_text(size=5)) + ggtitle("English monolingual categorizations of English speakers")
```

```{r}
plot_df %>%
  filter(group == "East Asian") %>% 
  filter(lang_1 == "English") %>% 
  ggplot(aes(x, y, color = lang_3, label = lang_3)) +
  geom_point(size = .8, alpha = .6) + 
  geom_text(size = 1.3, hjust = -.15) +
  stat_ellipse(aes(x, y, color = lang_2), level = .8, linetype = "dashed", alpha = .5) +
  theme_minimal() + 
  ylab("Dimension 1") +
  xlab("Dimension 2") +
  labs(color = "Language Group") +
  scale_color_manual(values=cbPalette) +
  theme(legend.position = "none", legend.text=element_text(size=5),
        legend.title=element_text(size=5)) + ggtitle("East Asian categorizations of English speakers")

```

```{r}
plot_df %>%
  filter(group == "South Asian") %>% 
  filter(lang_1 == "English") %>% 
  ggplot(aes(x, y, color = lang_3, label = lang_3)) +
  geom_point(size = .8, alpha = .6) + 
  geom_text(size = 1.3, hjust = -.15) +
  stat_ellipse(aes(x, y, color = lang_2), level = .8, linetype = "dashed", alpha = .5) +
  theme_minimal() + 
  ylab("Dimension 1") +
  xlab("Dimension 2") +
  labs(color = "Language Group") +
  scale_color_manual(values=cbPalette) +
  theme(legend.position = "none", legend.text=element_text(size=5),
        legend.title=element_text(size=5)) + ggtitle("South Asian categorizations of English speakers")

```

```{r}
plot_df %>%
  filter(group == "Southeast Asian") %>% 
  filter(lang_1 == "English") %>% 
  ggplot(aes(x, y, color = lang_3, label = lang_3)) +
  geom_point(size = .8, alpha = .6) + 
  geom_text(size = 1.3, hjust = -.15) +
  stat_ellipse(aes(x, y, color = lang_2), level = .8, linetype = "dashed", alpha = .5) +
  theme_minimal() + 
  ylab("Dimension 1") +
  xlab("Dimension 2") +
  labs(color = "Language Group") +
  scale_color_manual(values=cbPalette) +
  theme(legend.position = "none", legend.text=element_text(size=5),
        legend.title=element_text(size=5)) + ggtitle("Southeast Asian categorizations of English speakers")

```


```{r}
plot_df %>%
  filter(group == "Non multi") %>% 
  filter(lang_1 == "English") %>% 
  ggplot(aes(x, y, color = lang_3, label = lang_3)) +
  geom_point(size = .8, alpha = .6) + 
  geom_text(size = 1.3, hjust = -.15) +
  stat_ellipse(aes(x, y, color = lang_2), level = .8, linetype = "dashed", alpha = .5) +
  theme_minimal() + 
  ylab("Dimension 1") +
  xlab("Dimension 2") +
  labs(color = "Language Group") +
  scale_color_manual(values=cbPalette) +
  theme(legend.position = "none", legend.text=element_text(size=5),
        legend.title=element_text(size=5)) + ggtitle("Non-asian multilinguals categorizations of English speakers")

```